<?xml version="1.0" encoding="utf-8"?><Database Name="HRM" Class="HRMModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-PK221FL\SQLEXPRESS;Initial Catalog=HRM;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="HRMConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Absent" Member="Absents">
    <Type Name="Absent">
      <Column Name="AbsentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AbsentDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AbsentType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StaffID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Absent" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="StaffID" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BirthDay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardID" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Education" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ManagerID" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="DaysRemain" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="SectionID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Absent" Member="Absents" ThisKey="StaffID" OtherKey="StaffID" Type="Absent" />
      <Association Name="Staff_Account" Member="Accounts" ThisKey="StaffID" OtherKey="StaffID" Type="Account" />
      <Association Name="Staff_Contract" Member="Contracts" ThisKey="StaffID" OtherKey="StaffID" Type="Contract" />
      <Association Name="Staff_DaysRemain" Member="DaysRemains" ThisKey="StaffID" OtherKey="StaffID" Type="DaysRemain" />
      <Association Name="Staff_Salary" Member="Salaries" ThisKey="StaffID" OtherKey="StaffID" Type="Salary" />
      <Association Name="Staff_SocialInsurance" Member="SocialInsurances" ThisKey="StaffID" OtherKey="StaffID" Type="SocialInsurance" />
      <Association Name="Position_Staff" Member="Position" ThisKey="PostID" OtherKey="PostID" Type="Position" IsForeignKey="true" />
      <Association Name="Section_Staff" Member="Section" ThisKey="SectionID" OtherKey="SectionID" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Access" Member="Accesses">
    <Type Name="Access">
      <Column Name="AccessID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Form" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Edit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DescriptionAccess" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Access_DetailAccess" Member="DetailAccesses" ThisKey="AccessID" OtherKey="AccessID" Type="DetailAccess" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="Char(33)" CanBeNull="true" />
      <Column Name="GroupAccessID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Account" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
      <Association Name="GroupAccess_Account" Member="GroupAccess" ThisKey="GroupAccessID" OtherKey="GroupAccessID" Type="GroupAccess" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CateAge" Member="CateAges">
    <Type Name="CateAge">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="mount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contract" Member="Contracts">
    <Type Name="Contract">
      <Column Name="ContractID" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BasicPay" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Payment" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StaffID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="ContractTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Contract" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DaysRemain" Member="DaysRemains">
    <Type Name="DaysRemain">
      <Column Name="DaysRemainID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LeaveAYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsedInYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_DaysRemain" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetailAccess" Member="DetailAccesses">
    <Type Name="DetailAccess">
      <Column Name="AccessID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupAccessID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Access_DetailAccess" Member="Access" ThisKey="AccessID" OtherKey="AccessID" Type="Access" IsForeignKey="true" />
      <Association Name="GroupAccess_DetailAccess" Member="GroupAccess" ThisKey="GroupAccessID" OtherKey="GroupAccessID" Type="GroupAccess" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupAccess" Member="GroupAccesses">
    <Type Name="GroupAccess">
      <Column Name="GroupAccessID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupAccessName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="GroupAccess_Account" Member="Accounts" ThisKey="GroupAccessID" OtherKey="GroupAccessID" Type="Account" />
      <Association Name="GroupAccess_DetailAccess" Member="DetailAccesses" ThisKey="GroupAccessID" OtherKey="GroupAccessID" Type="DetailAccess" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Positions">
    <Type Name="Position">
      <Column Name="PostID" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PostName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Position_Staff" Member="Staffs" ThisKey="PostID" OtherKey="PostID" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.[Rule]" Member="Rules">
    <Type Name="Rule">
      <Column Name="RuleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SIPayRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LeaveAYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Salary" Member="Salaries">
    <Type Name="Salary">
      <Column Name="SalaryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BasicPay" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SalaryMonth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Workdays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Allowance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="AllowanceDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StandardWorkdays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RealPay" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="StaffID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Salary" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="SectionID" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StandardWorkdays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Association Name="Section_Staff" Member="Staffs" ThisKey="SectionID" OtherKey="SectionID" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.SocialInsurance" Member="SocialInsurances">
    <Type Name="SocialInsurance">
      <Column Name="InsuranceID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SIStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PayRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Payment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StaffID" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_SocialInsurance" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Age_Range" Method="Age_Range">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.test" Method="test">
    <ElementType Name="testResult">
      <Column Name="[&lt; 40]" Member="__40" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[&lt; 20]" Member="__20" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Sp_absent" Method="Sp_absent">
    <ElementType Name="Sp_absentResult">
      <Column Name="AbsentType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>