using DevExpress.XtraPivotGrid;

namespace HRM
{
    public partial class UcSalaryAl : DevExpress.XtraEditors.XtraUserControl
    {
        public UcSalaryAl()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            pivotTableAdapter.Fill(hRMDataSet.Pivot);
        }

        private void pivotGridControl1_FieldValueDisplayText(object sender, PivotFieldDisplayTextEventArgs e)
        {
            if (e.ValueType == PivotGridValueType.GrandTotal && !e.IsColumn)
            {
                e.DisplayText = "Tổng cộng";
            }
        }
    }
}
